version: '3.3'
services:
   db:
     image: mysql:5.7
     volumes:
       - db_data1:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: testdb1
       MYSQL_USER: testuser
       MYSQL_PASSWORD: root
     ports:
       - 3306:3306
volumes:
    db_data1:
           name: db_data1
